[project]
name = "crac-cloud"
version = "0.1.0"
description = "code in cloud for gui web, connecting to crac server via gRPC and FastAPI"
readme = "README.md"
license =  "MIT"
requires-python = ">=3.12"


dependencies = [
    # Client gRPC e Protobuf
    "grpcio >=1.64.1",
    "protobuf >=5.27.1",
    # Framework web e server
    "fastapi >=0.117.1",
    "uvicorn >=0.37.0",
    # Per gestire le variabili d'ambiente
    "python-dotenv >=1.1.1",
    "jinja2 >=3.1.6",
    "astropy", # Necessario per SkyCoord, EarthLocation e Time
    "astroplan", # Logica principale per la pianificazione e i plot
    "matplotlib", # Per generare i file immagine PNG (savefig)
    "numpy", # Dipendenza di Matplotlib e Astropy
    # Per connettersi a un repository GitHub come dipendenza
    "crac-protobuf @ git+https://github.com/ara-astronomia/crac-protobuf@16-create-new-proto-geographic-and-data_image",
    "astroquery>=0.4.11",
]

[tool.setuptools.packages.find]
exclude = [
    "static*",
    "templates*",
]

[project.optional-dependencies]
dev = [
    "grpcio-tools >=1.64",
    "autopep8 >=1.6",
    "pytest >=8.0",
    "httpx >=0.27",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

